### ISSUE TITLE
no audio heard, warning reINVITE 406 AudioIncompatible, linux container on kubernetes

### ISSUE THREAD

**Issue by f2calv** [sipsorcery-org/sipsorcery#1413]
We are moving/porting a working Windows SIP application to a Linux container running on Kubernetes in Azure.
 
The application is entirely custom and calls up end-users and relays an audio message to them, the audio message is generated via Azure AI Text To Speech Service, we create an audio Stream with the Raw8Khz16BitMonoPcm format.

The application works well on Windows, however when running in a container the end result is that the audio "plays" for X seconds (as long the given audio segment is) and then ends with "Send audio from stream completed." but no sound is actually heard at the receiver end we only see this "**INVITE 406 AudioIncompatible**" message.

We initialize our VoIPMediaSession as follows;
```c#
//initialize VoIPMediaSession session object 
var AudioMediaSession = new VoIPMediaSession(new VoIPMediaSessionConfig
{
    RtpSecureMediaOption = RtpSecureMediaOptionEnum.SdpCryptoNegotiation,
    MediaEndPoint = new MediaEndPoints()// { AudioSource = audioExtrasSource },
});
AudioMediaSession.AcceptRtpFromAny = true;
var audioExtrasSource = new AudioExtrasSource();
audioExtrasSource.SetSource(AudioSourcesEnum.Silence);
AudioMediaSession.addTrack(new MediaStreamTrack(audioExtrasSource.GetAudioSourceFormats()));
```
Then, when triggered, we retrieve the audio byte[] from Azure and use SendAudioFromStream to send it to the client, this is working well running on a Windows host.

```c#
///...triggering code redacted

//retrieve audio stream from Azure and send to client
Stream audioStream = await _textToSpeech.GenerateTextToSpeechStream("hello world");
await AudioMediaSession.AudioExtrasSource.SendAudioFromStream(audioStream, AudioSamplingRatesEnum.Rate8KHz);
```

The (redacted) logs from the call segment are as follows;

> 
> [14:33:20 INF] VoiceCallService tried to reach recipient for 5715.9663ms.
> [14:33:20 INF] VoiceCallService successfully reached recipient!
> [14:33:20 DBG] Request received: tls:10.19.2.208:30000<-tls:192.168.1.80:5721 INVITE sips:+123456789@10.19.2.208:30000 SIP/2.0
> [14:33:20 INF] SipTransportManager request received tls:10.19.2.208:30000<-tls:192.168.1.80:5721: INVITE sips:+123456789@10.19.2.208:30000 SIP/2.0
> [14:33:20 DBG] Re-INVITE request received INVITE sips:+123456789@10.19.2.208:30000 SIP/2.0.
> **[14:33:20 WRN] Unable to set remote description from reINVITE request AudioIncompatible**
> **[14:33:20 DBG] Response sent: tls:10.19.2.208:30000->tls:192.168.1.80:5721 INVITE 406 AudioIncompatible**
> [14:33:20 DBG] Request received: tls:10.19.2.208:30000<-tls:192.168.1.80:5721 ACK sips:+123456789@10.19.2.208:30000 SIP/2.0
> [14:33:21 INF] TextToSpeechAzureService initialized SpeechConfig object with authorizationToken
> [14:33:22 INF] TextToSpeechAzureService speech synthesized for text: [Hallo.XXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXXX]
> [14:33:22 DBG] Sending audio stream length 239200.
> [14:33:37 DBG] Send audio from stream completed.
> [14:33:40 DBG] Request received: tls:10.19.2.208:30000<-tls:192.168.1.80:5721 BYE sips:+123456789@10.19.2.208:30000 SIP/2.0
> [14:33:40 INF] SipTransportManager request received tls:10.19.2.208:30000<-tls:192.168.1.80:5721: BYE sips:+123456789@10.19.2.208:30000 SIP/2.0
> [14:33:40 INF] Remote call party hungup BYE sips:+123456789@10.19.2.208:30000 SIP/2.0.
> [14:33:40 DBG] Response sent: tls:10.19.2.208:30000->tls:192.168.1.80:5721 BYE 200 Ok
> [14:33:40 DBG] RTPChannel closing, RTP receiver on port 59510, Control receiver on port 59511. Reason: normal.
> 

I'm not a Sip wizard so I've simply containerized the working Windows application using a standard .NET 8 container image (mcr.microsoft.com/dotnet/aspnet:8.0).

Do I need to install any additional dependencies inside the container image to get the audio to work? I have seen the Ffmpeg nuget package exists, but as we already have the audio byte array I was assuming that we don't need this, as we can just stream the bytes?

I would really welcome any input or examples as running SipSorcery under linux seems to be not so popular...

Note: we are using SIPSorcery 6.2.4 due to some package updating constraints on our side.

**Comment by sipsorcery** [comment]
You don't need any other dependencies or to use the FFmpeg package. The audio codecs are simple enough that they can be implemented in C# and are included in the main SIPSorcery package.

First thing to try is to restrict the codecs you're supporting  to see if that helps. Try something like the below, note that part of the code has had a lot of fixes done since v6.2.4 so it's hard to say what will work and if you're encountering a bug or not:

```
var audioExtrasSource = new AudioExtrasSource();
audioExtrasSource.RestrictFormats(x => x.Codec == AudioCodecsEnum.PCMU);
```

Other than that turning on a SIP trace will reveal why the audio codec incompatability is occurring, use something like:

```
private static void EnableTraceLogs(SIPTransport sipTransport)
{
	sipTransport.SIPRequestInTraceEvent += (localEP, remoteEP, req) =>
	{
		Log.LogDebug($"Request received: {localEP}<-{remoteEP}");
		Log.LogDebug(req.ToString());
	};

	sipTransport.SIPRequestOutTraceEvent += (localEP, remoteEP, req) =>
	{
		Log.LogDebug($"Request sent: {localEP}->{remoteEP}");
		Log.LogDebug(req.ToString());
	};

	sipTransport.SIPResponseInTraceEvent += (localEP, remoteEP, resp) =>
	{
		Log.LogDebug($"Response received: {localEP}<-{remoteEP}");
		Log.LogDebug(resp.ToString());
	};

	sipTransport.SIPResponseOutTraceEvent += (localEP, remoteEP, resp) =>
	{
		Log.LogDebug($"Response sent: {localEP}->{remoteEP}");
		Log.LogDebug(resp.ToString());
	};

	sipTransport.SIPRequestRetransmitTraceEvent += (tx, req, count) =>
	{
		Log.LogDebug($"Request retransmit {count} for request {req.StatusLine}, initial transmit {DateTime.Now.Subtract(tx.InitialTransmit).TotalSeconds.ToString("0.###")}s ago.");
	};

	sipTransport.SIPResponseRetransmitTraceEvent += (tx, resp, count) =>
	{
		Log.LogDebug($"Response retransmit {count} for response {resp.ShortDescription}, initial transmit {DateTime.Now.Subtract(tx.InitialTransmit).TotalSeconds.ToString("0.###")}s ago.");
	};
}
```

I haven't looked at it for ages and no idea if it still works but in case it helps there is this repo [sipspeech](https://github.com/sipsorcery/sipspeech).

**Comment by sipsorcery** [comment]
It could be this warning:

`[14:06:28 WRN] RTP has timed out for media audio hanging up call.`

Do you know for sure UDP traffic works to/from your deployment?

I have a cloud based kubernetes cluster I can run a test with one of the sample apps on. It's working fine for WebRTC apps. I'll give it a try with one of the SIP apps shortly.

**Comment by sipsorcery** [comment]
I got the [SIPCallServer](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/SIPCallServer/Program.cs) app running in my k8s cluster and straight away the NAT issues started. It shows how long it's been since I've deployed a SIP server app. NAT was always one of the first things that cropped up. WebRTC deals with NAT much more robustly so I haven't had to deal with it for a while.

In my case the SIP INVITE arrived into my k8s app as:

```
[22:07:49 DBG] Request received: udp:0.0.0.0:5060<-udp:x.x.x.x:44540 INVITE sip:5@34.32.1.242 SIP/2.0
[22:07:49 VRB] Request: INVITE sip:5@34.32.1.242 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.123:5080;rport;branch=z9hG4bKPjb24ebbd4d2e64845bc87dfde77ec4649
To: <sip:5@34.32.1.242>
From: <sip:192.168.1.123>;tag=f23f41a90e7e40ea8d0751d322090660
Call-ID: a14b62f57462492892e214efed69f426
CSeq: 20187 INVITE
Contact: <sip:192.168.1.123:5080;ob>
Max-Forwards: 70
User-Agent: MicroSIP/3.21.6
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Content-Length: 318
Content-Type: application/sdp
Session-Expires: 1800
Min-SE: 90

v=0
o=- 3956944069 3956944069 IN IP4 192.168.1.123
s=pjmedia
b=AS:84
t=0 0
a=X-nat:0
m=audio 4004 RTP/AVP 8 101
c=IN IP4 192.168.1.123
b=TIAS:64000
a=rtcp:4005 IN IP4 192.168.1.123
a=sendrecv
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ssrc:800718884 cname:4648771b4aaf0cb8
```

The first problem is my server app in k8s does not now it's public IP so when it sends a SIP OK response the client cannot reach the private IP in the contact header. This can be solved in teh SIP serer code using:

```
if(Environment.GetEnvironmentVariable("SIP_CONTACT_HOST") != null)
{
	_sipTransport.ContactHost = Environment.GetEnvironmentVariable("SIP_CONTACT_HOST");
}          
```

That got the SIP call successfully set up for me.

The next problem is the private IP address used in the SDP. That prevents the audio being able to get to the client. It's due to this line in the INVITE request:

`c=IN IP4 192.168.1.123`

The way to deal with it is to use the `SIPPacketMangler.MangleSDP` method. I'll need some more time to go and dig up an example of wiring that up.

Here's my k8s manifest in case it's of any use for your testing:

```
apiVersion: v1
kind: Namespace
metadata:
  name: sip-callserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sipcallserver
  namespace: sip-callserver
  labels:
    app: sipcallserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sipcallserver
  template:
    metadata:
      labels:
        app: sipcallserver
    spec:
      containers:
      - name: sipcallserver
        image: sipsorcery/sipcallserver:0.3
        ports:
        - name: sip-udp
          containerPort: 5060
          protocol: UDP
        #- name: sip-tcp
        #  containerPort: 5061
        #  protocol: TCP
        # if your app needs any env vars, add them here
        env:
         - name: SIP_CONTACT_HOST
           value: "34.32.1.242"
---
apiVersion: v1
kind: Service
metadata:
  name: sipcallserver-lb
  namespace: sip-callserver
spec:
  type: LoadBalancer
  selector:
    app: sipcallserver
  externalTrafficPolicy: Local
  ports:
  - name: sip-udp
    protocol: UDP
    port: 5060
    targetPort: 5060
  #- name: sip-tcp
  #  protocol: TCP
  #  port: 5061
  #  targetPort: 5061
  # uncomment & set this if you’ve already reserved a static IP
  # loadBalancerIP: <YOUR_STATIC_IP>
```

**Comment by sipsorcery** [comment]
I eventually got RTP audio to/from my k8s deployment but not in a very ideal way. As alluded to above the BIG hurdle is NAT. The k8s load balancer/kube proxy does the NAT which is normally what you want as it allows k8s to load balance across pods.

The issue arises when the SIP client (UAC) is also behind a NAT. Now it gets very difficult to get an RTP packet from one side of the call to the other. The SDP contains the locally bound port but since tha port is being NATted it's useless. If one end is not behind NAT it can be managed but given that's normally the server end, in this case k8s, that does not apply.

The way I kludged it to work was to bind the RTP to a static port and then set up a rule for that in my k8s manifest. It means only a single call at a time can be processed.

The code mods are:

To get tke k8s Public IP address set in the SIP messages.

```
await ua.Answer(uas, rtpSession, IPAddress.Parse(_publicIPAddress));
```

To get k8s to bind to a static port:

```
var rtpAudioSession = new VoIPMediaSession(new MediaEndPoints { AudioSource = audioExtrasSource }, bindPort: bindPort);
```

The k8s manifest I used:

```
apiVersion: v1
kind: Namespace
metadata:
  name: sip-callserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sipcallserver
  namespace: sip-callserver
  labels:
    app: sipcallserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sipcallserver
  template:
    metadata:
      labels:
        app: sipcallserver
    spec:
      containers:
      - name: sipcallserver
        image: sipsorcery/sipcallserver:0.6
        env:
         - name: PUBLIC_IP_ADDRESS
           value: "34.32.1.242"
         - name: RTP_PORT
           value: "55342"
        ports:
        - name: sip-udp
          containerPort: 5060
          protocol: UDP
        - name: rtp-udp
          containerPort: 55342
          protocol: UDP
        - name: rtcp-udp
          containerPort: 55343
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: sipcallserver-lb
  namespace: sip-callserver
spec:
  type: LoadBalancer
  selector:
    app: sipcallserver
  externalTrafficPolicy: Local
  ports:
  - name: sip-udp
    protocol: UDP
    port: 5060
    targetPort: 5060
  - name: rtp-udp
    protocol: UDP
    port: 55342
    targetPort: 55342
  - name: rtcp-udp
    protocol: UDP
    port: 55343
    targetPort: 55343
```

If you have the luxury of being able to choose the client application this whole thing is way easier with WebRTC with no extra NAT handling required.

**Comment by sipsorcery** [comment]
This challenge got into my head and after a few days I did solve the issue, or at least my version of it. As described above the problem was entirely down to NAT. The k8s environment does prevent some NAT challenges with the standard networking modes which are typically geared for HTTP load balancing.

As a test you can call `sip:3@34.32.1.242` to get a sine wave tone (likely to be taken down 2-3 days after this post). The other side of the call is running in Google Cloud's GKE and this [demo app](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/SIPCloudCallServer/Program.cs).

The k8s manifest is below and to make it robustly it was necessary to add a firewall rule to permit ingress on all the node ephemeral UDP ports. The firewall rule is not needed if the client is using a full cone NAT.

```
apiVersion: v1
kind: Namespace
metadata:
  name: sipcloudcallserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sipcloudcallserver-dep
  namespace: sipcloudcallserver
  labels:
    app: sipcloudcallserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sipcloudcallserver
  template:
    metadata:
      labels:
        app: sipcloudcallserver
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: sipcloudcallserver
        image: sipsorcery/sipcloudcallserver:0.1
        env:
         - name: SIP_CONTACT_HOST
           value: "34.32.1.242"
         - name: STUN_URL
           value: "stun.cloudflare.com"
        ports:
        - name: sip-udp
          containerPort: 5060
          protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: sipcloudcallserver-lb
  namespace: sipcloudcallserver
spec:
  type: LoadBalancer
  selector:
    app: sipcloudcallserver
  externalTrafficPolicy: Local
  ports:
  - name: sip-udp
    protocol: UDP
    port: 5060
    targetPort: 5060
```

I don't believe there is any code issue with the library here so if there's no further info will close this issue.
